<!DOCTYPE html>
<html>
    <head>
        <title>
            <?= $_helper['block']('title') ?>
        </title>

        <?= $_helper['asset']->linkTag('application.css') ?>
    </head>
    <body>
        <header role="banner">
            <h1><a href="/">Welcome to Spark!</a></h1>
        </header>

        <div id="flash">
            <?php foreach ($_helper['flash']->get('notice', []) as $flash): ?>
            <div class="flash-notice">
                <?= $flash ?>
            </div>
            <?php endforeach ?>
        </div>

        <section role="main">
            <?= $_helper['block']('content') ?>
        </section>

        <footer>
            <p>Powered by <a href="http://github.com/CHH/spark">Spark Framework</a></p>
        </footer>

        <?= $_helper['asset']->linkTag('application.js') ?>
    </body>
</html>

