var tree = [["Spark","Spark.html","",
                [["Controller","Spark\/Controller.html","",
                [["EventListener","Spark\/Controller\/EventListener.html","",
                [["AutoViewRender","Spark\/Controller\/EventListener\/AutoViewRender.html","",
                [        ]],["ControllerClassResolver","Spark\/Controller\/EventListener\/ControllerClassResolver.html","",
                [        ]]        ]],["Base","Spark\/Controller\/Base.html","",
                [        ]],["ControllerCollection","Spark\/Controller\/ControllerCollection.html"," < ControllerCollection",
                [        ]],["ControllerServiceProvider","Spark\/Controller\/ControllerServiceProvider.html","",
                [        ]],["RenderPipeline","Spark\/Controller\/RenderPipeline.html","",
                [        ]],["ViewContext","Spark\/Controller\/ViewContext.html","",
                [        ]]        ]],["Core","Spark\/Core.html","",
                [["Command","Spark\/Core\/Command.html","",
                [["CreateApplication","Spark\/Core\/Command\/CreateApplication.html"," < Command",
                [        ]],["Generate","Spark\/Core\/Command\/Generate.html"," < Command",
                [        ]],["QueueWorker","Spark\/Core\/Command\/QueueWorker.html"," < WorkCommand",
                [        ]],["Server","Spark\/Core\/Command\/Server.html"," < Command",
                [        ]],["Upgrade","Spark\/Core\/Command\/Upgrade.html"," < Command",
                [        ]]        ]],["Generator","Spark\/Core\/Generator.html","",
                [["AbstractGenerator","Spark\/Core\/Generator\/AbstractGenerator.html","",
                [        ]],["ControllerGenerator","Spark\/Core\/Generator\/ControllerGenerator.html"," < AbstractGenerator",
                [        ]],["GeneratorInterface","Spark\/Core\/Generator\/GeneratorInterface.html","",
                [        ]]        ]],["ApplicationAware","Spark\/Core\/ApplicationAware.html","",
                [        ]],["Bootstrap","Spark\/Core\/Bootstrap.html","",
                [        ]],["Cli","Spark\/Core\/Cli.html","",
                [        ]],["ConfigBuilder","Spark\/Core\/ConfigBuilder.html"," < Pimple",
                [        ]],["CoreServiceProvider","Spark\/Core\/CoreServiceProvider.html","",
                [        ]],["DevelopmentServer","Spark\/Core\/DevelopmentServer.html","",
                [        ]],["Job","Spark\/Core\/Job.html","",
                [        ]],["WebTestCase","Spark\/Core\/WebTestCase.html"," < WebTestCase",
                [        ]]        ]],["Exception","Spark\/Exception.html","",
                [["InvalidArgumentException","Spark\/Exception\/InvalidArgumentException.html"," < InvalidArgumentException",
                [        ]],["RuntimeException","Spark\/Exception\/RuntimeException.html"," < RuntimeException",
                [        ]],["UnexpectedValueException","Spark\/Exception\/UnexpectedValueException.html"," < UnexpectedValueException",
                [        ]]        ]],["Model","Spark\/Model.html","",
                [["AssertBuilder","Spark\/Model\/AssertBuilder.html","",
                [        ]],["Base","Spark\/Model\/Base.html","",
                [        ]],["BehaviorInterface","Spark\/Model\/BehaviorInterface.html","",
                [        ]],["ConstraintsBuilder","Spark\/Model\/ConstraintsBuilder.html","",
                [        ]]        ]],["Support","Spark\/Support.html","",
                [["Strings","Spark\/Support\/Strings.html","",
                [        ]]        ]],["Application","Spark\/Application.html"," < Application",
                [        ]],["Exception","Spark\/Exception.html","",
                [        ]],["Spark","Spark\/Spark.html","",
                [        ]]        ]]        ]

